### ISSUE TITLE
Crash on startup 1.12.2

### ISSUE THREAD

**Issue by SuperDoggo** [PC-Logix/OpenSecurity#106]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  SoundUnpack (OpenSecurity-MC1.12.2-1.0-9.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 7/26/18 11:06 PM
Description: Initializing game

java.lang.NoSuchMethodError: net.minecraftforge.fml.common.registry.GameRegistry.registerTileEntity(Ljava/lang/Class;Lnet/minecraft/util/ResourceLocation;)V
	at pcl.opensecurity.common.ContentRegistry.registerTileEntity(ContentRegistry.java:120)
	at pcl.opensecurity.common.ContentRegistry.registerBlocks(ContentRegistry.java:104)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_4_ContentRegistry_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:734)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:639)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at pcl.opensecurity.common.ContentRegistry.registerTileEntity(ContentRegistry.java:120)
	at pcl.opensecurity.common.ContentRegistry.registerBlocks(ContentRegistry.java:104)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_4_ContentRegistry_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:734)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:639)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 180561584 bytes (172 MB) / 367464448 bytes (350 MB) up to 21461467136 bytes (20467 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx20G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2673 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                 | Version      | Source                              | Signature                                |
	|:----- |:------------------ |:------------ |:----------------------------------- |:---------------------------------------- |
	| UCH   | minecraft          | 1.12.2       | minecraft.jar                       | None                                     |
	| UCH   | mcp                | 9.42         | minecraft.jar                       | None                                     |
	| UCH   | FML                | 8.0.99.99    | forge-1.12.2-14.23.3.2673.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge              | 14.23.3.2673 | forge-1.12.2-14.23.3.2673.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | opencomputers|core | 1.7.2.67     | minecraft.jar                       | None                                     |
	| UCH   | opencomputers      | 1.7.2.67     | OpenComputers-MC1.12.2-1.7.2.67.jar | None                                     |
	| UCH   | opensecurity       | 1.0-9        | OpenSecurity-MC1.12.2-1.0-9.jar     | None                                     |

	Loaded coremods (and transformers): 
TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  li.cil.oc.common.asm.ClassTransformer
SoundUnpack (OpenSecurity-MC1.12.2-1.0-9.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.05' Renderer: 'GeForce 820M/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.3.2673
	LWJGL: 2.9.4
	OpenGL: GeForce 820M/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.05, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'vanilla,skl28'
	Type: Client (map_client.txt)
	Resource Packs: Faithful 1.12.2-rv4
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz

**Comment by CaitlynMainer** [comment]
Update forge, you're using 14.23.3.2673 OS is built against 14.23.4.2705.
If this is still an issue after updating forge, please reopen and comment but I'm running it on 14.23.4.2705 with no issue right now.
