### ISSUE TITLE
MC1.12.2-1.0-12 - MC Client Crash

### ISSUE THREAD

**Issue by mc-oc** [PC-Logix/OpenSecurity#109]
When importing the MC1.12.2-1.0-12 module into the client the following crash prevents MC from loading.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  SoundUnpack (OpenSecurity-MC1.12.2-1.0-12.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 7/31/18 5:58 PM
Description: Initializing game

java.lang.NoSuchMethodError: net.minecraftforge.fml.common.registry.GameRegistry.registerTileEntity(Ljava/lang/Class;Lnet/minecraft/util/ResourceLocation;)V
	at pcl.opensecurity.common.ContentRegistry.registerTileEntity(ContentRegistry.java:120)
	at pcl.opensecurity.common.ContentRegistry.registerBlocks(ContentRegistry.java:104)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_7_ContentRegistry_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:734)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:603)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at pcl.opensecurity.common.ContentRegistry.registerTileEntity(ContentRegistry.java:120)
	at pcl.opensecurity.common.ContentRegistry.registerBlocks(ContentRegistry.java:104)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_7_ContentRegistry_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:734)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:603)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 479692272 bytes (457 MB) / 1023410176 bytes (976 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.0.2529 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                 | Version      | Source                                | Signature                                |
	|:----- |:------------------ |:------------ |:------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft          | 1.12.2       | minecraft.jar                         | None                                     |
	| UCH   | mcp                | 9.42         | minecraft.jar                         | None                                     |
	| UCH   | FML                | 8.0.99.99    | forge-1.12.2-14.23.0.2529.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge              | 14.23.0.2529 | forge-1.12.2-14.23.0.2529.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | opencomputers|core | 1.7.2.67     | minecraft.jar                         | None                                     |
	| UCH   | mercurius_updater  | 1.0          | MercuriusUpdater-1.12.2.jar           | None                                     |
	| UCH   | ic2                | 2.8.73-ex112 | industrialcraft-2-2.8.73-ex112.jar    | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCH   | opencomputers      | 1.7.2.67     | OpenComputers-MC1.12.2-1.7.2.67.jar   | None                                     |
	| UCH   | opensecurity       | 1.0-12       | OpenSecurity-MC1.12.2-1.0-12.jar      | None                                     |
	| UCH   | worldedit          | 6.1.8        | worldedit-forge-mc1.12-6.1.8-dist.jar | None                                     |

	Loaded coremods (and transformers): 
SoundUnpack (OpenSecurity-MC1.12.2-1.0-12.jar)
  
TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  li.cil.oc.common.asm.ClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 22.20.16.4708' Renderer: 'Intel(R) HD Graphics 630'
	Launched Version: 1.12.2-forge1.12.2-14.23.0.2529
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 630 GL version 4.4.0 - Build 22.20.16.4708, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7820HK CPU @ 2.90GHz

**Comment by CaitlynMainer** [comment]
Update forge and try again please.

**Comment by mc-oc** [comment]
Attempted 1.12.2 - 14.23.4.2747 with no success.

**Comment by CaitlynMainer** [comment]
I'm running Forge 14.23.4.2705, the method you are showing as missing was added in 14.23.3.2694
https://drive.pc-logix.com/index.php/s/766WyGgQ4W5qka8  Here I am with the game loaded showing various versions OS I'm using is built against the source for the .12 release

**Comment by mc-oc** [comment]
I was able to get OpenSecurity-MC1.12.2-1.0-10 to run with Forge 14.23.4.2705 but OpenSecurity-1.7.10-1.0-114 continued to crash. Thank you for the support!

**Comment by mc-oc** [comment]
Issue closed, not reproducible. Work around identified.
