### ISSUE TITLE
[Bug] Crash when trying to break door

### ISSUE THREAD

**Issue by drzpk** [PC-Logix/OpenSecurity#142]
**Describe the bug**
After placing a rolldoor block I tried to break it and the game crashed

**In which environment did the Bug appear?**
Singleplayer,

**To Reproduce**
1. Place rolldoor block
2. Attempt to break it
3. Wait for crash as soon as breaking particles appear

**Minecraft:**
 - Mod Version: OpenSecurity-MC1.12.2-1.0-25
 - Minecraft Version: 1.12.2
 - Forge Version: forge1.12.2-14.23.5.2838

**Additional context**

Crash stack trace:
```
[19:40:11] [Client thread/FATAL] [minecraft/Minecraft]: Unreported exception thrown!
java.lang.RuntimeException: Missing particle!
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.func_177645_b(SimpleBakedModel.java:157) ~[cgf$a.class:?]
	at net.minecraftforge.client.ForgeHooksClient.getDamageModel(ForgeHooksClient.java:835) ~[ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175020_a(BlockRendererDispatcher.java:46) ~[bvm.class:?]
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175020_a(CCBlockRendererDispatcher.java:53) ~[CCBlockRendererDispatcher.class:?]
	at gcewing.sg.BaseAORenderingManager$CustomBlockRendererDispatcher.func_175020_a(BaseAORenderingManager.java:76) ~[BaseAORenderingManager$CustomBlockRendererDispatcher.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_174981_a(RenderGlobal.java:2788) ~[buy.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1844) ~[buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613) ~[buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1384) ~[buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

Full crashlog: [crash-2019-09-27_19.40.11-client.txt](https://github.com/PC-Logix/OpenSecurity/files/3663971/crash-2019-09-27_19.40.11-client.txt)

**Comment by ben-mkiv** [comment]
so i was able to reproduce it once, but now not anymore. does this bug always happen to you? If so, could you please try to camouflage the controller with any block (rightclick with stone for example) and report back if it still happens?

this build might fix the bug... (feedback is appreciated)
http://ci.pc-logix.com/job/OpenSecurity-1.12/37/artifact/build/libs/OpenSecurity-MC1.12.2-1.0-37.jar

**Comment by ben-mkiv** [comment]
theres now a new version on curseForge which includes the fix.

Thanks for reporting it!
